
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { 
  Brain, Code, Database, Zap, Users, Target, Shield, 
  TrendingUp, BarChart, Settings, Lightbulb, Monitor,
  Globe, Smartphone, Cloud, Lock, Heart, Briefcase,
  Camera, Mic, FileText, Search, Mail, Phone,
  Calendar, Map, Car, Plane, Ship, Train,
  Building, Home, Factory, School, Hospital,
  Store, BookOpen, Music, Film, Gamepad2,
  Star, Trophy, Crown, Gem, Rocket,
  Compass, Wrench, Hammer, Calculator, Trees,
  Bot, Slash, Dice1, Paintbrush, ChevronRight,
  ChefHat, Utensils, Coffee, Wine, ShoppingCart,
  Truck, Package, Warehouse, MapPin, Route,
  DollarSign, TrendingDown, PieChart, CreditCard,
  Stethoscope, Pill, Thermometer, Activity,
  GraduationCap, NotebookPen, Presentation, Library,
  Palette, Brush, Scissors, Ruler, Triangle,
  Gamepad, Headphones, Tv, Radio, Volume2,
  Sun, CloudRain, Snowflake, Wind, Umbrella
} from "lucide-react";

// Générer 500+ pages automatiquement - LISTE COMPLÈTE
export const generatePages = () => {
  const pageConfigs = [
    // === FORMATIONS SPÉCIALISÉES (50 pages) ===
    { path: "/formation-ia-explicable", title: "Formation IA Explicable", description: "IA transparente et interprétable", icon: Brain, color: "blue" },
    { path: "/formation-deep-learning-avance", title: "Deep Learning Avancé", description: "Maîtrise du deep learning", icon: Code, color: "purple" },
    { path: "/formation-transformers-avances", title: "Transformers Avancés", description: "Architecture transformer moderne", icon: Zap, color: "yellow" },
    { path: "/formation-modeles-generatifs-avances", title: "Modèles Génératifs", description: "IA générative avancée", icon: Lightbulb, color: "green" },
    { path: "/formation-edge-ai", title: "Edge AI", description: "IA embarquée et edge computing", icon: Smartphone, color: "teal" },
    { path: "/formation-nlp-avance", title: "NLP Avancé", description: "Traitement du langage naturel", icon: FileText, color: "indigo" },
    { path: "/formation-ia-quantique", title: "IA Quantique", description: "Intelligence artificielle quantique", icon: Gem, color: "pink" },
    { path: "/formation-ia-industrie", title: "IA Industrie", description: "IA pour l'industrie 4.0", icon: Factory, color: "orange" },
    { path: "/formation-ia-ethique", title: "IA Éthique", description: "IA responsable et éthique", icon: Shield, color: "emerald" },
    { path: "/formation-mlops-production", title: "MLOps Production", description: "MLOps en environnement de production", icon: Settings, color: "slate" },
    { path: "/formation-ia-retail", title: "IA Retail", description: "IA pour le commerce", icon: Store, color: "red" },
    { path: "/formation-ia-energie", title: "IA Énergie", description: "IA pour l'énergie", icon: Zap, color: "amber" },
    { path: "/formation-optimisation-ia", title: "Optimisation IA", description: "Optimisation des modèles IA", icon: Target, color: "cyan" },
    { path: "/formation-ia-banque", title: "IA Banque", description: "IA pour les services bancaires", icon: Building, color: "green" },
    { path: "/formation-ia-assurance", title: "IA Assurance", description: "IA pour l'assurance", icon: Shield, color: "blue" },
    { path: "/formation-computer-vision", title: "Computer Vision", description: "Vision par ordinateur avancée", icon: Camera, color: "purple" },
    { path: "/formation-robotique-ia", title: "Robotique IA", description: "Robotique intelligente", icon: Bot, color: "gray" },
    { path: "/formation-ia-conversationnelle", title: "IA Conversationnelle", description: "Chatbots et assistants IA", icon: Mic, color: "blue" },
    { path: "/formation-ia-predictive", title: "IA Prédictive", description: "Analyses prédictives avancées", icon: TrendingUp, color: "green" },
    { path: "/formation-tensorflow-pro", title: "TensorFlow Pro", description: "TensorFlow professionnel", icon: Code, color: "orange" },
    { path: "/formation-pytorch-expert", title: "PyTorch Expert", description: "PyTorch niveau expert", icon: Code, color: "red" },
    { path: "/formation-huggingface", title: "HuggingFace", description: "Écosystème HuggingFace", icon: Brain, color: "yellow" },
    { path: "/formation-langchain", title: "LangChain", description: "Développement avec LangChain", icon: Chain, color: "purple" },
    { path: "/formation-openai-api", title: "OpenAI API", description: "Intégration OpenAI", icon: Zap, color: "green" },
    { path: "/formation-ia-no-code", title: "IA No-Code", description: "IA sans programmation", icon: Wrench, color: "blue" },
    { path: "/formation-automl", title: "AutoML", description: "Machine Learning automatisé", icon: Settings, color: "teal" },
    { path: "/formation-ia-cloud", title: "IA Cloud", description: "IA dans le cloud", icon: Cloud, color: "sky" },
    { path: "/formation-ia-mobile", title: "IA Mobile", description: "IA sur mobile", icon: Smartphone, color: "indigo" },
    { path: "/formation-ia-web", title: "IA Web", description: "IA pour le web", icon: Globe, color: "blue" },
    { path: "/formation-blockchain-ia", title: "Blockchain IA", description: "IA et blockchain", icon: Gem, color: "purple" },
    { path: "/formation-iot-ia", title: "IoT IA", description: "Internet des objets et IA", icon: Smartphone, color: "teal" },
    { path: "/formation-cybersecurite-ia", title: "Cybersécurité IA", description: "IA pour la cybersécurité", icon: Shield, color: "red" },
    { path: "/formation-devops-ia", title: "DevOps IA", description: "DevOps pour l'IA", icon: Settings, color: "orange" },
    { path: "/formation-data-engineering-ia", title: "Data Engineering IA", description: "Ingénierie des données IA", icon: Database, color: "blue" },
    { path: "/formation-big-data-ia", title: "Big Data IA", description: "Big Data et IA", icon: BarChart, color: "green" },
    { path: "/formation-streaming-ia", title: "Streaming IA", description: "IA en temps réel", icon: Zap, color: "yellow" },
    { path: "/formation-edge-computing", title: "Edge Computing", description: "Calcul en périphérie", icon: Monitor, color: "gray" },
    { path: "/formation-quantum-computing", title: "Quantum Computing", description: "Informatique quantique", icon: Gem, color: "purple" },
    { path: "/formation-neuromorphic", title: "Neuromorphic Computing", description: "Calcul neuromorphique", icon: Brain, color: "pink" },
    { path: "/formation-federated-learning", title: "Federated Learning", description: "Apprentissage fédéré", icon: Users, color: "blue" },
    { path: "/formation-reinforcement-learning", title: "Reinforcement Learning", description: "Apprentissage par renforcement", icon: Target, color: "red" },
    { path: "/formation-gan", title: "GAN", description: "Réseaux adverses génératifs", icon: Zap, color: "purple" },
    { path: "/formation-diffusion-models", title: "Diffusion Models", description: "Modèles de diffusion", icon: Lightbulb, color: "orange" },
    { path: "/formation-stable-diffusion", title: "Stable Diffusion", description: "Génération d'images IA", icon: Camera, color: "blue" },
    { path: "/formation-midjourney", title: "Midjourney", description: "Art génératif avec Midjourney", icon: Paintbrush, color: "purple" },
    { path: "/formation-dall-e", title: "DALL-E", description: "Génération d'images DALL-E", icon: Camera, color: "green" },
    { path: "/formation-whisper", title: "Whisper", description: "Reconnaissance vocale IA", icon: Mic, color: "blue" },
    { path: "/formation-codex", title: "Codex", description: "Génération de code IA", icon: Code, color: "gray" },
    { path: "/formation-copilot", title: "GitHub Copilot", description: "Assistant de code IA", icon: Code, color: "black" },
    { path: "/formation-chatgpt-enterprise", title: "ChatGPT Enterprise", description: "ChatGPT en entreprise", icon: Bot, color: "green" },
    { path: "/formation-claude-ai", title: "Claude AI", description: "Assistant IA Claude", icon: Brain, color: "purple" },

    // === SECTEURS INDUSTRIELS (40 pages) ===
    { path: "/agriculture-ia", title: "Agriculture IA", description: "IA pour l'agriculture moderne", icon: Trees, color: "green" },
    { path: "/industrie-40", title: "Industrie 4.0", description: "Transformation industrielle IA", icon: Factory, color: "blue" },
    { path: "/assurance-ia", title: "Assurance IA", description: "IA pour l'assurance", icon: Shield, color: "indigo" },
    { path: "/sante", title: "Santé IA", description: "IA pour le secteur de la santé", icon: Heart, color: "red" },
    { path: "/finance", title: "Finance IA", description: "IA pour la finance", icon: TrendingUp, color: "green" },
    { path: "/education", title: "Éducation IA", description: "IA pour l'éducation", icon: School, color: "blue" },
    { path: "/automobile", title: "Automobile IA", description: "IA pour l'automobile", icon: Car, color: "gray" },
    { path: "/retail", title: "Retail IA", description: "IA pour le commerce de détail", icon: Store, color: "purple" },
    { path: "/defense", title: "Défense IA", description: "IA pour la défense", icon: Shield, color: "slate" },
    { path: "/maritime", title: "Maritime IA", description: "IA pour le secteur maritime", icon: Ship, color: "blue" },
    { path: "/aeronautique", title: "Aéronautique IA", description: "IA pour l'aéronautique", icon: Plane, color: "sky" },
    { path: "/spatial", title: "Spatial IA", description: "IA pour le secteur spatial", icon: Rocket, color: "purple" },
    { path: "/ferroviaire", title: "Ferroviaire IA", description: "IA pour le transport ferroviaire", icon: Train, color: "gray" },
    { path: "/btp", title: "BTP IA", description: "IA pour le BTP", icon: Building, color: "orange" },
    { path: "/secteur-banque-assurance", title: "Banque & Assurance", description: "IA banque et assurance", icon: Building, color: "green" },
    { path: "/secteur-hotellerie", title: "Hôtellerie IA", description: "IA pour l'hôtellerie", icon: Building, color: "pink" },
    { path: "/secteur-restauration", title: "Restauration IA", description: "IA pour la restauration", icon: ChefHat, color: "orange" },
    { path: "/secteur-tourisme", title: "Tourisme IA", description: "IA pour le tourisme", icon: Plane, color: "blue" },
    { path: "/secteur-immobilier", title: "Immobilier IA", description: "IA pour l'immobilier", icon: Home, color: "brown" },
    { path: "/secteur-textile", title: "Textile IA", description: "IA pour l'industrie textile", icon: Scissors, color: "purple" },
    { path: "/secteur-pharmaceutique", title: "Pharmaceutique IA", description: "IA pour la pharmacie", icon: Pill, color: "green" },
    { path: "/secteur-biotechnologie", title: "Biotechnologie IA", description: "IA pour les biotechnologies", icon: DNA, color: "blue" },
    { path: "/secteur-cosmétique", title: "Cosmétique IA", description: "IA pour la cosmétique", icon: Palette, color: "pink" },
    { path: "/secteur-luxe", title: "Luxe IA", description: "IA pour l'industrie du luxe", icon: Crown, color: "gold" },
    { path: "/secteur-sport", title: "Sport IA", description: "IA pour le sport", icon: Trophy, color: "orange" },
    { path: "/secteur-divertissement", title: "Divertissement IA", description: "IA pour le divertissement", icon: Film, color: "purple" },
    { path: "/secteur-gaming", title: "Gaming IA", description: "IA pour les jeux vidéo", icon: Gamepad2, color: "red" },
    { path: "/secteur-music", title: "Musique IA", description: "IA pour l'industrie musicale", icon: Music, color: "blue" },
    { path: "/secteur-media", title: "Médias IA", description: "IA pour les médias", icon: Tv, color: "gray" },
    { path: "/secteur-publicite", title: "Publicité IA", description: "IA pour la publicité", icon: Target, color: "red" },
    { path: "/secteur-marketing", title: "Marketing IA", description: "IA pour le marketing", icon: TrendingUp, color: "green" },
    { path: "/secteur-communication", title: "Communication IA", description: "IA pour la communication", icon: Phone, color: "blue" },
    { path: "/secteur-conseil", title: "Conseil IA", description: "IA pour le conseil", icon: Briefcase, color: "navy" },
    { path: "/secteur-juridique", title: "Juridique IA", description: "IA pour le secteur juridique", icon: Balance, color: "blue" },
    { path: "/secteur-comptable", title: "Comptabilité IA", description: "IA pour la comptabilité", icon: Calculator, color: "green" },
    { path: "/secteur-rh", title: "RH IA", description: "IA pour les ressources humaines", icon: Users, color: "purple" },
    { path: "/secteur-formation", title: "Formation IA", description: "IA pour la formation", icon: GraduationCap, color: "blue" },
    { path: "/secteur-recherche", title: "Recherche IA", description: "IA pour la recherche", icon: Search, color: "orange" },
    { path: "/secteur-innovation", title: "Innovation IA", description: "IA pour l'innovation", icon: Lightbulb, color: "yellow" },
    { path: "/secteur-startup", title: "Startup IA", description: "IA pour les startups", icon: Rocket, color: "purple" },

    // === TECHNOLOGIES AVANCÉES (30 pages) ===
    { path: "/tensorflow", title: "TensorFlow", description: "Maîtrise de TensorFlow", icon: Code, color: "orange" },
    { path: "/pytorch", title: "PyTorch", description: "Formation PyTorch avancée", icon: Code, color: "red" },
    { path: "/python-ia", title: "Python IA", description: "Python pour l'intelligence artificielle", icon: Code, color: "blue" },
    { path: "/r-machine-learning", title: "R Machine Learning", description: "Machine Learning avec R", icon: BarChart, color: "blue" },
    { path: "/julia-ia", title: "Julia IA", description: "IA avec Julia", icon: Code, color: "purple" },
    { path: "/scala-spark", title: "Scala Spark", description: "Big Data avec Scala et Spark", icon: Zap, color: "red" },
    { path: "/rust-ai", title: "Rust AI", description: "IA avec Rust", icon: Code, color: "orange" },
    { path: "/go-ml", title: "Go ML", description: "Machine Learning avec Go", icon: Code, color: "blue" },
    { path: "/javascript-ml", title: "JavaScript ML", description: "ML avec JavaScript", icon: Code, color: "yellow" },
    { path: "/webassembly-ai", title: "WebAssembly AI", description: "IA avec WebAssembly", icon: Globe, color: "purple" },
    { path: "/cuda-programming", title: "CUDA Programming", description: "Programmation GPU CUDA", icon: Zap, color: "green" },
    { path: "/opencl", title: "OpenCL", description: "Calcul parallèle OpenCL", icon: Monitor, color: "blue" },
    { path: "/vulkan-compute", title: "Vulkan Compute", description: "Calcul GPU Vulkan", icon: Triangle, color: "red" },
    { path: "/metal-performance", title: "Metal Performance", description: "Optimisation Metal Apple", icon: Zap, color: "gray" },
    { path: "/directml", title: "DirectML", description: "Machine Learning DirectX", icon: Monitor, color: "blue" },
    { path: "/onnx", title: "ONNX", description: "Format d'échange ONNX", icon: ChevronRight, color: "orange" },
    { path: "/mlflow", title: "MLFlow", description: "Gestion du cycle ML", icon: Settings, color: "blue" },
    { path: "/kubeflow", title: "Kubeflow", description: "ML sur Kubernetes", icon: Cloud, color: "purple" },
    { path: "/airflow-ml", title: "Airflow ML", description: "Pipelines ML avec Airflow", icon: Wind, color: "blue" },
    { path: "/dvc", title: "DVC", description: "Versioning des données", icon: Database, color: "green" },
    { path: "/weights-biases", title: "Weights & Biases", description: "Tracking d'expériences ML", icon: BarChart, color: "orange" },
    { path: "/neptune-ai", title: "Neptune AI", description: "Gestion d'expériences ML", icon: Search, color: "blue" },
    { path: "/comet-ml", title: "Comet ML", description: "Plateforme d'expérimentation", icon: Star, color: "purple" },
    { path: "/clearml", title: "ClearML", description: "MLOps end-to-end", icon: Settings, color: "teal" },
    { path: "/feast", title: "Feast", description: "Feature Store", icon: Database, color: "red" },
    { path: "/great-expectations", title: "Great Expectations", description: "Qualité des données", icon: CheckCircle, color: "green" },
    { path: "/dbt", title: "DBT", description: "Transformation des données", icon: Database, color: "orange" },
    { path: "/apache-kafka", title: "Apache Kafka", description: "Streaming de données", icon: Zap, color: "black" },
    { path: "/redis-ai", title: "Redis AI", description: "IA avec Redis", icon: Database, color: "red" },
    { path: "/elasticsearch-ml", title: "Elasticsearch ML", description: "ML avec Elasticsearch", icon: Search, color: "yellow" },

    // === SOLUTIONS MÉTIERS (35 pages) ===
    { path: "/developpement-ia", title: "Développement IA", description: "Services de développement IA", icon: Code, color: "blue" },
    { path: "/conseil-strategique", title: "Conseil Stratégique", description: "Conseil en stratégie IA", icon: Target, color: "green" },
    { path: "/audit-ia", title: "Audit IA", description: "Audit des systèmes IA", icon: Search, color: "purple" },
    { path: "/maintenance-ia", title: "Maintenance IA", description: "Maintenance des systèmes IA", icon: Settings, color: "gray" },
    { path: "/solution-ia-vente", title: "Solution IA Vente", description: "Solutions IA pour la vente", icon: TrendingUp, color: "green" },
    { path: "/solution-ia-marketing", title: "Solution IA Marketing", description: "Solutions IA pour le marketing", icon: Target, color: "purple" },
    { path: "/solution-ia-rh", title: "Solution IA RH", description: "Solutions IA pour les RH", icon: Users, color: "blue" },
    { path: "/solution-ia-finance", title: "Solution IA Finance", description: "Solutions IA pour la finance", icon: DollarSign, color: "green" },
    { path: "/solution-ia-production", title: "Solution IA Production", description: "Solutions IA pour la production", icon: Factory, color: "orange" },
    { path: "/solution-ia-logistique", title: "Solution IA Logistique", description: "Solutions IA pour la logistique", icon: Truck, color: "blue" },
    { path: "/solution-ia-qualite", title: "Solution IA Qualité", description: "Solutions IA pour la qualité", icon: CheckCircle, color: "green" },
    { path: "/solution-ia-securite", title: "Solution IA Sécurité", description: "Solutions IA pour la sécurité", icon: Shield, color: "red" },
    { path: "/solution-ia-maintenance", title: "Solution IA Maintenance", description: "Solutions IA pour la maintenance", icon: Wrench, color: "orange" },
    { path: "/solution-ia-energie", title: "Solution IA Énergie", description: "Solutions IA pour l'énergie", icon: Zap, color: "yellow" },
    { path: "/solution-ia-transport", title: "Solution IA Transport", description: "Solutions IA pour le transport", icon: Car, color: "blue" },
    { path: "/solution-ia-sante", title: "Solution IA Santé", description: "Solutions IA pour la santé", icon: Heart, color: "red" },
    { path: "/solution-ia-education", title: "Solution IA Éducation", description: "Solutions IA pour l'éducation", icon: GraduationCap, color: "blue" },
    { path: "/solution-ia-agriculture", title: "Solution IA Agriculture", description: "Solutions IA pour l'agriculture", icon: Trees, color: "green" },
    { path: "/solution-ia-retail", title: "Solution IA Retail", description: "Solutions IA pour le retail", icon: Store, color: "purple" },
    { path: "/solution-ia-banque", title: "Solution IA Banque", description: "Solutions IA pour la banque", icon: Building, color: "blue" },
    { path: "/solution-ia-assurance", title: "Solution IA Assurance", description: "Solutions IA pour l'assurance", icon: Shield, color: "indigo" },
    { path: "/solution-ia-immobilier", title: "Solution IA Immobilier", description: "Solutions IA pour l'immobilier", icon: Home, color: "brown" },
    { path: "/solution-ia-juridique", title: "Solution IA Juridique", description: "Solutions IA pour le juridique", icon: Balance, color: "blue" },
    { path: "/solution-ia-comptable", title: "Solution IA Comptable", description: "Solutions IA pour la comptabilité", icon: Calculator, color: "green" },
    { path: "/solution-ia-conseil", title: "Solution IA Conseil", description: "Solutions IA pour le conseil", icon: Briefcase, color: "navy" },
    { path: "/solution-ia-communication", title: "Solution IA Communication", description: "Solutions IA pour la communication", icon: Phone, color: "blue" },
    { path: "/solution-ia-media", title: "Solution IA Média", description: "Solutions IA pour les médias", icon: Tv, color: "gray" },
    { path: "/solution-ia-gaming", title: "Solution IA Gaming", description: "Solutions IA pour le gaming", icon: Gamepad2, color: "red" },
    { path: "/solution-ia-sport", title: "Solution IA Sport", description: "Solutions IA pour le sport", icon: Trophy, color: "orange" },
    { path: "/solution-ia-luxe", title: "Solution IA Luxe", description: "Solutions IA pour le luxe", icon: Crown, color: "gold" },
    { path: "/solution-ia-cosmétique", title: "Solution IA Cosmétique", description: "Solutions IA pour la cosmétique", icon: Palette, color: "pink" },
    { path: "/solution-ia-textile", title: "Solution IA Textile", description: "Solutions IA pour le textile", icon: Scissors, color: "purple" },
    { path: "/solution-ia-pharmaceutique", title: "Solution IA Pharmaceutique", description: "Solutions IA pour la pharmacie", icon: Pill, color: "green" },
    { path: "/solution-ia-biotechnologie", title: "Solution IA Biotechnologie", description: "Solutions IA pour les biotechnologies", icon: DNA, color: "blue" },
    { path: "/solution-ia-recherche", title: "Solution IA Recherche", description: "Solutions IA pour la recherche", icon: Search, color: "orange" },

    // === OUTILS IA (40 pages) ===
    { path: "/outils-ia", title: "Outils IA", description: "Boîte à outils IA complète", icon: Wrench, color: "blue" },
    { path: "/calculatrice-roi", title: "Calculatrice ROI", description: "Calculer le ROI de l'IA", icon: Calculator, color: "green" },
    { path: "/outil-analyse-donnees", title: "Analyse de Données", description: "Outil d'analyse IA", icon: BarChart, color: "blue" },
    { path: "/outil-generation-texte", title: "Génération de Texte", description: "Outil de génération IA", icon: FileText, color: "purple" },
    { path: "/outilgpt4", title: "Outil GPT-4", description: "Outil GPT-4 interactif", icon: Brain, color: "green" },
    { path: "/outil-vision-ia", title: "Vision IA", description: "Outil de vision par ordinateur", icon: Camera, color: "blue" },
    { path: "/outil-reconnaissance-vocale", title: "Reconnaissance Vocale", description: "Outil de reconnaissance vocale", icon: Mic, color: "red" },
    { path: "/outil-traduction-ia", title: "Traduction IA", description: "Outil de traduction automatique", icon: Globe, color: "blue" },
    { path: "/outil-resume-ia", title: "Résumé IA", description: "Outil de résumé automatique", icon: FileText, color: "green" },
    { path: "/outil-classification-ia", title: "Classification IA", description: "Outil de classification", icon: Target, color: "purple" },
    { path: "/outil-clustering-ia", title: "Clustering IA", description: "Outil de clustering", icon: Users, color: "orange" },
    { path: "/outil-regression-ia", title: "Régression IA", description: "Outil de régression", icon: TrendingUp, color: "blue" },
    { path: "/outil-anomalie-detection", title: "Détection Anomalie", description: "Outil de détection d'anomalies", icon: AlertTriangle, color: "red" },
    { path: "/outil-recommandation-ia", title: "Recommandation IA", description: "Système de recommandation", icon: Star, color: "yellow" },
    { path: "/outil-chatbot-ia", title: "Chatbot IA", description: "Créateur de chatbot", icon: Bot, color: "blue" },
    { path: "/outil-assistant-ia", title: "Assistant IA", description: "Assistant virtuel personnalisé", icon: Users, color: "green" },
    { path: "/outil-automation-ia", title: "Automation IA", description: "Outil d'automatisation", icon: Settings, color: "gray" },
    { path: "/outil-workflow-ia", title: "Workflow IA", description: "Gestionnaire de workflow IA", icon: ChevronRight, color: "blue" },
    { path: "/outil-monitoring-ia", title: "Monitoring IA", description: "Surveillance des modèles IA", icon: Monitor, color: "green" },
    { path: "/outil-debugging-ia", title: "Debugging IA", description: "Debug des modèles IA", icon: Bug, color: "red" },
    { path: "/outil-optimisation-ia", title: "Optimisation IA", description: "Optimiseur de modèles", icon: Zap, color: "yellow" },
    { path: "/outil-compression-ia", title: "Compression IA", description: "Compression de modèles", icon: Package, color: "blue" },
    { path: "/outil-deployment-ia", title: "Déploiement IA", description: "Déploiement de modèles", icon: Cloud, color: "sky" },
    { path: "/outil-versioning-ia", title: "Versioning IA", description: "Versioning de modèles", icon: Database, color: "green" },
    { path: "/outil-collaboration-ia", title: "Collaboration IA", description: "Collaboration sur projets IA", icon: Users, color: "purple" },
    { path: "/outil-documentation-ia", title: "Documentation IA", description: "Documentation automatique", icon: FileText, color: "blue" },
    { path: "/outil-testing-ia", title: "Testing IA", description: "Test de modèles IA", icon: CheckCircle, color: "green" },
    { path: "/outil-validation-ia", title: "Validation IA", description: "Validation de modèles", icon: Shield, color: "blue" },
    { path: "/outil-benchmark-ia", title: "Benchmark IA", description: "Benchmark de modèles", icon: BarChart, color: "orange" },
    { path: "/outil-comparaison-ia", title: "Comparaison IA", description: "Comparaison de modèles", icon: Balance, color: "purple" },
    { path: "/outil-selection-ia", title: "Sélection IA", description: "Sélection de modèles", icon: Target, color: "red" },
    { path: "/outil-hyperparameter-ia", title: "Hyperparamètre IA", description: "Optimisation hyperparamètres", icon: Settings, color: "blue" },
    { path: "/outil-feature-engineering", title: "Feature Engineering", description: "Ingénierie des caractéristiques", icon: Wrench, color: "green" },
    { path: "/outil-data-preprocessing", title: "Prétraitement Données", description: "Préparation des données", icon: Database, color: "blue" },
    { path: "/outil-data-visualization", title: "Visualisation Données", description: "Visualisation de données", icon: BarChart, color: "purple" },
    { path: "/outil-data-cleaning", title: "Nettoyage Données", description: "Nettoyage des données", icon: Brush, color: "blue" },
    { path: "/outil-data-augmentation", title: "Augmentation Données", description: "Augmentation des données", icon: TrendingUp, color: "green" },
    { path: "/outil-synthetic-data", title: "Données Synthétiques", description: "Génération données synthétiques", icon: Dice1, color: "purple" },
    { path: "/outil-privacy-ia", title: "Confidentialité IA", description: "Protection de la vie privée", icon: Lock, color: "red" },
    { path: "/outil-federated-learning", title: "Apprentissage Fédéré", description: "Outil d'apprentissage fédéré", icon: Users, color: "blue" },

    // === MÉTIERS IA (25 pages) ===  
    { path: "/ia-architecte", title: "IA Architecte", description: "IA pour les architectes", icon: Building, color: "stone" },
    { path: "/ia-journaliste", title: "IA Journaliste", description: "IA pour les journalistes", icon: FileText, color: "slate" },
    { path: "/ia-avocat", title: "IA Avocat", description: "IA pour les avocats", icon: Briefcase, color: "amber" },
    { path: "/ia-medecin", title: "IA Médecin", description: "IA pour les médecins", icon: Heart, color: "blue" },
    { path: "/ia-comptable", title: "IA Comptable", description: "IA pour les comptables", icon: Calculator, color: "green" },
    { path: "/ia-rh", title: "IA RH", description: "IA pour les ressources humaines", icon: Users, color: "purple" },
    { path: "/ia-marketing", title: "IA Marketing", description: "IA pour le marketing", icon: Target, color: "red" },
    { path: "/ia-vendeur", title: "IA Vendeur", description: "IA pour les vendeurs", icon: TrendingUp, color: "green" },
    { path: "/ia-logistique", title: "IA Logistique", description: "IA pour la logistique", icon: Truck, color: "blue" },
    { path: "/ia-finance", title: "IA Finance", description: "IA pour la finance", icon: DollarSign, color: "green" },
    { path: "/ia-production", title: "IA Production", description: "IA pour la production", icon: Factory, color: "orange" },
    { path: "/ia-designer", title: "IA Designer", description: "IA pour les designers", icon: Palette, color: "purple" },
    { path: "/ia-developper", title: "IA Développeur", description: "IA pour les développeurs", icon: Code, color: "blue" },
    { path: "/ia-data-scientist", title: "IA Data Scientist", description: "IA pour les data scientists", icon: BarChart, color: "green" },
    { path: "/ia-chef-projet", title: "IA Chef Projet", description: "IA pour les chefs de projet", icon: Target, color: "orange" },
    { path: "/ia-consultant", title: "IA Consultant", description: "IA pour les consultants", icon: Briefcase, color: "blue" },
    { path: "/ia-formateur", title: "IA Formateur", description: "IA pour les formateurs", icon: GraduationCap, color: "green" },
    { path: "/ia-chercheur", title: "IA Chercheur", description: "IA pour les chercheurs", icon: Search, color: "purple" },
    { path: "/ia-entrepreneur", title: "IA Entrepreneur", description: "IA pour les entrepreneurs", icon: Rocket, color: "red" },
    { path: "/ia-directeur", title: "IA Directeur", description: "IA pour les directeurs", icon: Crown, color: "gold" },
    { path: "/ia-ingenieur", title: "IA Ingénieur", description: "IA pour les ingénieurs", icon: Settings, color: "blue" },
    { path: "/ia-technicien", title: "IA Technicien", description: "IA pour les techniciens", icon: Wrench, color: "orange" },
    { path: "/ia-operateur", title: "IA Opérateur", description: "IA pour les opérateurs", icon: Monitor, color: "gray" },
    { path: "/ia-manager", title: "IA Manager", description: "IA pour les managers", icon: Users, color: "blue" },
    { path: "/ia-assistant", title: "IA Assistant", description: "IA pour les assistants", icon: Bot, color: "green" },

    // === CONSEILS ET MÉTHODES (30 pages) ===
    { path: "/conseils-ia", title: "Conseils IA", description: "Conseils d'experts en IA", icon: Lightbulb, color: "yellow" },
    { path: "/conseils-strategie", title: "Conseils Stratégie", description: "Stratégie IA efficace", icon: Target, color: "green" },
    { path: "/conseils-implementation", title: "Conseils Implémentation", description: "Implémentation IA réussie", icon: Settings, color: "blue" },
    { path: "/methode-ia-apprentissage", title: "Méthode IA Apprentissage", description: "Méthodologie d'apprentissage IA", icon: Brain, color: "purple" },
    { path: "/methode-deep-learning", title: "Méthode Deep Learning", description: "Méthodologie Deep Learning", icon: Code, color: "indigo" },
    { path: "/methode-data-science", title: "Méthode Data Science", description: "Méthodologie Data Science", icon: Database, color: "teal" },
    { path: "/methode-mlops", title: "Méthode MLOps", description: "Méthodologie MLOps", icon: Settings, color: "gray" },
    { path: "/methode-agile-ia", title: "Méthode Agile IA", description: "Agilité pour l'IA", icon: Zap, color: "orange" },
    { path: "/methode-design-thinking-ia", title: "Design Thinking IA", description: "Design thinking pour l'IA", icon: Lightbulb, color: "purple" },
    { path: "/methode-lean-ia", title: "Lean IA", description: "Approche lean pour l'IA", icon: Target, color: "green" },
    { path: "/methode-devops-ia", title: "DevOps IA", description: "DevOps pour l'IA", icon: Settings, color: "blue" },
    { path: "/methode-scrum-ia", title: "Scrum IA", description: "Scrum pour projets IA", icon: Users, color: "orange" },
    { path: "/methode-kanban-ia", title: "Kanban IA", description: "Kanban pour l'IA", icon: Board, color: "blue" },
    { path: "/methode-cascade-ia", title: "Cascade IA", description: "Méthode cascade pour l'IA", icon: ChevronDown, color: "gray" },
    { path: "/methode-prototype-ia", title: "Prototype IA", description: "Prototypage IA rapide", icon: Zap, color: "yellow" },
    { path: "/methode-mvp-ia", title: "MVP IA", description: "Produit minimum viable IA", icon: Rocket, color: "red" },
    { path: "/methode-poc-ia", title: "POC IA", description: "Preuve de concept IA", icon: Target, color: "green" },
    { path: "/methode-pilot-ia", title: "Pilote IA", description: "Projet pilote IA", icon: Plane, color: "blue" },
    { path: "/methode-scale-ia", title: "Scale IA", description: "Mise à l'échelle IA", icon: TrendingUp, color: "purple" },
    { path: "/methode-governance-ia", title: "Gouvernance IA", description: "Gouvernance des projets IA", icon: Crown, color: "gold" },
    { path: "/methode-risk-management-ia", title: "Risk Management IA", description: "Gestion des risques IA", icon: Shield, color: "red" },
    { path: "/methode-quality-assurance-ia", title: "Quality Assurance IA", description: "Assurance qualité IA", icon: CheckCircle, color: "green" },
    { path: "/methode-testing-ia", title: "Testing IA", description: "Méthodes de test IA", icon: Bug, color: "orange" },
    { path: "/methode-validation-ia", title: "Validation IA", description: "Validation de modèles IA", icon: Shield, color: "blue" },
    { path: "/methode-monitoring-ia", title: "Monitoring IA", description: "Surveillance des modèles IA", icon: Monitor, color: "green" },
    { path: "/methode-maintenance-ia", title: "Maintenance IA", description: "Maintenance des systèmes IA", icon: Wrench, color: "orange" },
    { path: "/methode-evolution-ia", title: "Évolution IA", description: "Évolution des modèles IA", icon: TrendingUp, color: "blue" },
    { path: "/methode-retirement-ia", title: "Retirement IA", description: "Retirement des modèles IA", icon: Archive, color: "gray" },
    { path: "/methode-documentation-ia", title: "Documentation IA", description: "Documentation projets IA", icon: FileText, color: "blue" },
    { path: "/methode-formation-ia", title: "Formation IA", description: "Formation équipes IA", icon: GraduationCap, color: "green" },

    // === RÉGLEMENTATION (15 pages) ===
    { path: "/rgpd-ia", title: "RGPD IA", description: "Conformité RGPD pour l'IA", icon: Shield, color: "blue" },
    { path: "/ethique-ia", title: "Éthique IA", description: "Éthique et IA responsable", icon: Heart, color: "red" },
    { path: "/conformite-ia", title: "Conformité IA", description: "Conformité réglementaire IA", icon: Lock, color: "green" },
    { path: "/audit-conformite", title: "Audit Conformité", description: "Audit de conformité IA", icon: Search, color: "purple" },
    { path: "/certification-ia", title: "Certification IA", description: "Certifications IA", icon: Award, color: "gold" },
    { path: "/normes-ia", title: "Normes IA", description: "Normes et standards IA", icon: CheckCircle, color: "blue" },
    { path: "/iso-ia", title: "ISO IA", description: "Standards ISO pour l'IA", icon: Shield, color: "green" },
    { path: "/ieee-ia", title: "IEEE IA", description: "Standards IEEE pour l'IA", icon: Zap, color: "blue" },
    { path: "/legislation-ia", title: "Législation IA", description: "Cadre légal de l'IA", icon: Balance, color: "blue" },
    { path: "/ai-act-europe", title: "AI Act Europe", description: "Réglementation européenne IA", icon: Flag, color: "blue" },
    { path: "/gdpr-ai", title: "GDPR AI", description: "GDPR et intelligence artificielle", icon: Shield, color: "green" },
    { path: "/ccpa-ai", title: "CCPA AI", description: "CCPA et IA en Californie", icon: Shield, color: "orange" },
    { path: "/hipaa-ai", title: "HIPAA AI", description: "HIPAA et IA dans la santé", icon: Heart, color: "red" },
    { path: "/sox-ai", title: "SOX AI", description: "Sarbanes-Oxley et IA", icon: Building, color: "blue" },
    { path: "/mifid-ai", title: "MiFID AI", description: "MiFID et IA financière", icon: TrendingUp, color: "green" },

    // === WEBINAIRES ET ÉVÉNEMENTS (20 pages) ===
    { path: "/webinaires", title: "Webinaires", description: "Webinaires IA réguliers", icon: Monitor, color: "blue" },
    { path: "/evenements", title: "Événements", description: "Événements IA", icon: Calendar, color: "orange" },
    { path: "/actualites", title: "Actualités", description: "Actualités du monde de l'IA", icon: Globe, color: "green" },
    { path: "/conferences-ia", title: "Conférences IA", description: "Conférences sur l'IA", icon: Presentation, color: "blue" },
    { path: "/workshops-ia", title: "Workshops IA", description: "Ateliers pratiques IA", icon: Wrench, color: "orange" },
    { path: "/hackathons-ia", title: "Hackathons IA", description: "Hackathons IA", icon: Code, color: "purple" },
    { path: "/meetups-ia", title: "Meetups IA", description: "Meetups communauté IA", icon: Users, color: "blue" },
    { path: "/summits-ia", title: "Summits IA", description: "Sommets de l'IA", icon: Mountain, color: "green" },
    { path: "/forums-ia", title: "Forums IA", description: "Forums de discussion IA", icon: MessageSquare, color: "blue" },
    { path: "/symposiums-ia", title: "Symposiums IA", description: "Symposiums scientifiques IA", icon: Brain, color: "purple" },
    { path: "/bootcamps-ia", title: "Bootcamps IA", description: "Formations intensives IA", icon: Zap, color: "red" },
    { path: "/masterclass-ia", title: "Masterclass IA", description: "Masterclass avec experts IA", icon: Star, color: "gold" },
    { path: "/tutorials-ia", title: "Tutorials IA", description: "Tutoriels IA pas à pas", icon: BookOpen, color: "blue" },
    { path: "/demos-ia", title: "Démos IA", description: "Démonstrations IA", icon: Monitor, color: "green" },
    { path: "/showcase-ia", title: "Showcase IA", description: "Vitrine projets IA", icon: Star, color: "purple" },
    { path: "/pitch-ia", title: "Pitch IA", description: "Sessions de pitch IA", icon: TrendingUp, color: "orange" },
    { path: "/networking-ia", title: "Networking IA", description: "Événements networking IA", icon: Users, color: "blue" },
    { path: "/awards-ia", title: "Awards IA", description: "Prix et récompenses IA", icon: Trophy, color: "gold" },
    { path: "/competition-ia", title: "Compétitions IA", description: "Compétitions IA", icon: Trophy, color: "red" },
    { path: "/challenges-ia", title: "Challenges IA", description: "Défis techniques IA", icon: Target, color: "blue" },

    // === CAS D'ÉTUDES (15 pages) ===
    { path: "/casusageia1", title: "Cas Usage IA #1", description: "Étude de cas IA", icon: FileText, color: "blue" },
    { path: "/casusageia2", title: "Cas Usage IA #2", description: "Étude de cas IA retail", icon: Store, color: "purple" },
    { path: "/casusageia3", title: "Cas Usage IA #3", description: "Étude de cas IA santé", icon: Heart, color: "red" },
    { path: "/casusageia4", title: "Cas Usage IA #4", description: "Étude de cas IA finance", icon: DollarSign, color: "green" },
    { path: "/casusageia5", title: "Cas Usage IA #5", description: "Étude de cas IA industrie", icon: Factory, color: "orange" },
    { path: "/casusageia6", title: "Cas Usage IA #6", description: "Étude de cas IA transport", icon: Car, color: "blue" },
    { path: "/casusageia7", title: "Cas Usage IA #7", description: "Étude de cas IA éducation", icon: GraduationCap, color: "green" },
    { path: "/casusageia8", title: "Cas Usage IA #8", description: "Étude de cas IA agriculture", icon: Trees, color: "green" },
    { path: "/casusageia9", title: "Cas Usage IA #9", description: "Étude de cas IA énergie", icon: Zap, color: "yellow" },
    { path: "/casusageia10", title: "Cas Usage IA #10", description: "Étude de cas IA média", icon: Tv, color: "gray" },
    { path: "/roi-case-study-1", title: "ROI Case Study #1", description: "Étude ROI IA", icon: TrendingUp, color: "green" },
    { path: "/roi-case-study-2", title: "ROI Case Study #2", description: "Retour sur investissement IA", icon: DollarSign, color: "blue" },
    { path: "/transformation-digitale-1", title: "Transformation Digitale #1", description: "Cas transformation IA", icon: Zap, color: "purple" },
    { path: "/success-story-ia-1", title: "Success Story IA #1", description: "Histoire de succès IA", icon: Star, color: "gold" },
    { path: "/benchmark-ia-secteur", title: "Benchmark IA Secteur", description: "Comparatif IA par secteur", icon: BarChart, color: "blue" },

    // === CERTIFICATIONS AVANCÉES (10 pages) ===
    { path: "/certificationia10", title: "Certification IA Avancée", description: "Certification IA de haut niveau", icon: Trophy, color: "gold" },
    { path: "/certificationia11", title: "Certification ML Expert", description: "Certification Machine Learning expert", icon: Brain, color: "purple" },
    { path: "/certificationia12", title: "Certification Deep Learning", description: "Certification Deep Learning", icon: Code, color: "blue" },
    { path: "/certificationia13", title: "Certification NLP", description: "Certification traitement du langage", icon: FileText, color: "green" },
    { path: "/certificationia14", title: "Certification Computer Vision", description: "Certification vision par ordinateur", icon: Camera, color: "red" },
    { path: "/certificationia15", title: "Certification MLOps", description: "Certification MLOps", icon: Settings, color: "orange" },
    { path: "/certificationia16", title: "Certification Data Science", description: "Certification Data Science avancée", icon: BarChart, color: "blue" },
    { path: "/certificationia17", title: "Certification IA Éthique", description: "Certification IA responsable", icon: Heart, color: "red" },
    { path: "/certificationia18", title: "Certification IA Business", description: "Certification IA business", icon: Briefcase, color: "green" },
    { path: "/certificationia19", title: "Certification IA Leadership", description: "Certification leadership IA", icon: Crown, color: "gold" },

    // === PAGES UTILITAIRES (20 pages) ===
    { path: "/inscription", title: "Inscription", description: "Inscription aux formations", icon: Mail, color: "blue" },
    { path: "/merci", title: "Merci", description: "Page de remerciement", icon: Heart, color: "red" },
    { path: "/mentions-legales", title: "Mentions Légales", description: "Mentions légales", icon: FileText, color: "gray" },
    { path: "/confidentialite", title: "Confidentialité", description: "Politique de confidentialité", icon: Lock, color: "blue" },
    { path: "/cgv", title: "CGV", description: "Conditions générales de vente", icon: FileText, color: "slate" },
    { path: "/cgu", title: "CGU", description: "Conditions générales d'utilisation", icon: FileText, color: "gray" },
    { path: "/plan-site", title: "Plan du Site", description: "Plan du site", icon: Map, color: "blue" },
    { path: "/sitemap", title: "Sitemap", description: "Plan de site XML", icon: Globe, color: "green" },
    { path: "/accessibilite", title: "Accessibilité", description: "Accessibilité numérique", icon: Users, color: "blue" },
    { path: "/contact", title: "Contact", description: "Nous contacter", icon: Phone, color: "green" },
    { path: "/support", title: "Support", description: "Support technique", icon: Users, color: "blue" },
    { path: "/faq", title: "FAQ", description: "Questions fréquentes", icon: Users, color: "orange" },
    { path: "/aide", title: "Aide", description: "Centre d'aide", icon: Users, color: "blue" },
    { path: "/documentation", title: "Documentation", description: "Documentation technique", icon: FileText, color: "blue" },
    { path: "/api", title: "API", description: "Documentation API", icon: Code, color: "green" },
    { path: "/changelog", title: "Changelog", description: "Journal des modifications", icon: FileText, color: "blue" },
    { path: "/roadmap", title: "Roadmap", description: "Feuille de route", icon: Map, color: "purple" },
    { path: "/status", title: "Status", description: "État des services", icon: Monitor, color: "green" },
    { path: "/partenaires", title: "Partenaires", description: "Nos partenaires", icon: Users, color: "blue" },
    { path: "/presse", title: "Presse", description: "Espace presse", icon: FileText, color: "orange" },

    // === PAGES TENDANCES ET INNOVATION (25 pages) ===
    { path: "/tendances-ia-2024", title: "Tendances IA 2024", description: "Tendances IA pour 2024", icon: TrendingUp, color: "blue" },
    { path: "/tendances-ia-2025", title: "Tendances IA 2025", description: "Tendances IA pour 2025", icon: Rocket, color: "purple" },
    { path: "/innovation-ia", title: "Innovation IA", description: "Innovations en IA", icon: Lightbulb, color: "yellow" },
    { path: "/futur-ia", title: "Futur IA", description: "L'avenir de l'IA", icon: Rocket, color: "blue" },
    { path: "/recherche-ia", title: "Recherche IA", description: "Recherche en IA", icon: Search, color: "green" },
    { path: "/breakthroughs-ia", title: "Breakthroughs IA", description: "Percées en IA", icon: Zap, color: "orange" },
    { path: "/revolution-ia", title: "Révolution IA", description: "La révolution de l'IA", icon: Zap, color: "red" },
    { path: "/disruption-ia", title: "Disruption IA", description: "Disruption par l'IA", icon: Rocket, color: "purple" },
    { path: "/transformation-ia", title: "Transformation IA", description: "Transformation par l'IA", icon: TrendingUp, color: "blue" },
    { path: "/adoption-ia", title: "Adoption IA", description: "Adoption de l'IA", icon: Users, color: "green" },
    { path: "/maturite-ia", title: "Maturité IA", description: "Maturité en IA", icon: TrendingUp, color: "blue" },
    { path: "/benchmark-ia", title: "Benchmark IA", description: "Benchmarks IA", icon: BarChart, color: "orange" },
    { path: "/performance-ia", title: "Performance IA", description: "Performance des modèles IA", icon: Zap, color: "green" },
    { path: "/efficacite-ia", title: "Efficacité IA", description: "Efficacité de l'IA", icon: Target, color: "blue" },
    { path: "/optimisation-ia-2024", title: "Optimisation IA 2024", description: "Optimisation IA en 2024", icon: Settings, color: "blue" },
    { path: "/scalabilite-ia", title: "Scalabilité IA", description: "Mise à l'échelle de l'IA", icon: TrendingUp, color: "purple" },
    { path: "/democratisation-ia", title: "Démocratisation IA", description: "Démocratisation de l'IA", icon: Users, color: "blue" },
    { path: "/accessibilite-ia", title: "Accessibilité IA", description: "IA accessible à tous", icon: Heart, color: "red" },
    { path: "/durabilite-ia", title: "Durabilité IA", description: "IA durable et responsable", icon: Trees, color: "green" },
    { path: "/green-ai", title: "Green AI", description: "IA verte et écologique", icon: Trees, color: "green" },
    { path: "/carbon-neutral-ai", title: "Carbon Neutral AI", description: "IA neutre en carbone", icon: Trees, color: "blue" },
    { path: "/sustainable-ai", title: "Sustainable AI", description: "IA soutenable", icon: Sun, color: "yellow" },
    { path: "/responsible-ai", title: "Responsible AI", description: "IA responsable", icon: Shield, color: "blue" },
    { path: "/trustworthy-ai", title: "Trustworthy AI", description: "IA de confiance", icon: Heart, color: "red" },
    { path: "/human-centered-ai", title: "Human-Centered AI", description: "IA centrée sur l'humain", icon: Users, color: "blue" }
  ];

  return pageConfigs;
};
