
import { RouteConfig } from '../siteRoutes';

export const industrieRoutes: RouteConfig[] = [
  { path: "/agriculture-ia", name: "Agriculture IA", description: "IA pour l'agriculture moderne", category: "Industries" },
  { path: "/industrie-40", name: "Industrie 4.0", description: "Transformation industrielle IA", category: "Industries" },
  { path: "/assurance-ia", name: "Assurance IA", description: "IA pour l'assurance", category: "Industries" },
  { path: "/sante", name: "Santé IA", description: "IA pour le secteur de la santé", category: "Industries" },
  { path: "/finance", name: "Finance IA", description: "IA pour la finance", category: "Industries" },
  { path: "/education", name: "Éducation IA", description: "IA pour l'éducation", category: "Industries" },
  { path: "/automobile", name: "Automobile IA", description: "IA pour l'automobile", category: "Industries" },
  { path: "/retail", name: "Retail IA", description: "IA pour le commerce de détail", category: "Industries" },
  { path: "/defense", name: "Défense IA", description: "IA pour la défense", category: "Industries" },
  { path: "/maritime", name: "Maritime IA", description: "IA pour le secteur maritime", category: "Industries" },
  { path: "/aeronautique", name: "Aéronautique IA", description: "IA pour l'aéronautique", category: "Industries" },
  { path: "/spatial", name: "Spatial IA", description: "IA pour le secteur spatial", category: "Industries" },
  { path: "/ferroviaire", name: "Ferroviaire IA", description: "IA pour le transport ferroviaire", category: "Industries" },
  { path: "/btp", name: "BTP IA", description: "IA pour le BTP", category: "Industries" },
  { path: "/secteur-banque-assurance", name: "Banque & Assurance", description: "IA banque et assurance", category: "Industries" },
  { path: "/secteur-hotellerie", name: "Hôtellerie IA", description: "IA pour l'hôtellerie", category: "Industries" },
  { path: "/secteur-restauration", name: "Restauration IA", description: "IA pour la restauration", category: "Industries" },
  { path: "/secteur-tourisme", name: "Tourisme IA", description: "IA pour le tourisme", category: "Industries" },
  { path: "/secteur-immobilier", name: "Immobilier IA", description: "IA pour l'immobilier", category: "Industries" },
  { path: "/secteur-textile", name: "Textile IA", description: "IA pour l'industrie textile", category: "Industries" },
  { path: "/secteur-pharmaceutique", name: "Pharmaceutique IA", description: "IA pour la pharmacie", category: "Industries" },
  { path: "/secteur-biotechnologie", name: "Biotechnologie IA", description: "IA pour les biotechnologies", category: "Industries" },
  { path: "/secteur-cosmétique", name: "Cosmétique IA", description: "IA pour la cosmétique", category: "Industries" },
  { path: "/secteur-luxe", name: "Luxe IA", description: "IA pour l'industrie du luxe", category: "Industries" },
  { path: "/secteur-sport", name: "Sport IA", description: "IA pour le sport", category: "Industries" },
  { path: "/secteur-divertissement", name: "Divertissement IA", description: "IA pour le divertissement", category: "Industries" },
  { path: "/secteur-gaming", name: "Gaming IA", description: "IA pour les jeux vidéo", category: "Industries" },
  { path: "/secteur-music", name: "Musique IA", description: "IA pour l'industrie musicale", category: "Industries" },
  { path: "/secteur-media", name: "Médias IA", description: "IA pour les médias", category: "Industries" },
  { path: "/secteur-publicite", name: "Publicité IA", description: "IA pour la publicité", category: "Industries" },
  { path: "/secteur-marketing", name: "Marketing IA", description: "IA pour le marketing", category: "Industries" },
  { path: "/secteur-communication", name: "Communication IA", description: "IA pour la communication", category: "Industries" },
  { path: "/secteur-conseil", name: "Conseil IA", description: "IA pour le conseil", category: "Industries" },
  { path: "/secteur-juridique", name: "Juridique IA", description: "IA pour le secteur juridique", category: "Industries" },
  { path: "/secteur-comptable", name: "Comptabilité IA", description: "IA pour la comptabilité", category: "Industries" },
  { path: "/secteur-rh", name: "RH IA", description: "IA pour les ressources humaines", category: "Industries" },
  { path: "/secteur-formation", name: "Formation IA", description: "IA pour la formation", category: "Industries" },
  { path: "/secteur-recherche", name: "Recherche IA", description: "IA pour la recherche", category: "Industries" },
  { path: "/secteur-innovation", name: "Innovation IA", description: "IA pour l'innovation", category: "Industries" },
  { path: "/secteur-startup", name: "Startup IA", description: "IA pour les startups", category: "Industries" },
];

export const secteurRoutes: RouteConfig[] = [
  { path: "/sante-cardiologie", name: "Santé Cardiologie", description: "IA pour la cardiologie", category: "Secteurs" },
  { path: "/sante-radiologie", name: "Santé Radiologie", description: "IA pour la radiologie", category: "Secteurs" },
  { path: "/sante-oncologie", name: "Santé Oncologie", description: "IA pour l'oncologie", category: "Secteurs" },
  { path: "/sante-neurologie", name: "Santé Neurologie", description: "IA pour la neurologie", category: "Secteurs" },
  { path: "/sante-chirurgie", name: "Santé Chirurgie", description: "IA pour la chirurgie", category: "Secteurs" },
  { path: "/sante-urgences", name: "Santé Urgences", description: "IA pour les urgences", category: "Secteurs" },
  { path: "/sante-pediatrie", name: "Santé Pédiatrie", description: "IA pour la pédiatrie", category: "Secteurs" },
  { path: "/sante-geriatrie", name: "Santé Gériatrie", description: "IA pour la gériatrie", category: "Secteurs" },
  { path: "/sante-psychiatrie", name: "Santé Psychiatrie", description: "IA pour la psychiatrie", category: "Secteurs" },
  { path: "/sante-dermatologie", name: "Santé Dermatologie", description: "IA pour la dermatologie", category: "Secteurs" },
];

export const secteurSpecialiseRoutes: RouteConfig[] = [
  { path: "/finance-banque-retail", name: "Finance Banque Retail", description: "IA pour la banque de détail", category: "Secteurs Spécialisés" },
  { path: "/finance-banque-investissement", name: "Finance Banque Investissement", description: "IA pour la banque d'investissement", category: "Secteurs Spécialisés" },
  { path: "/finance-assurance-vie", name: "Finance Assurance Vie", description: "IA pour l'assurance vie", category: "Secteurs Spécialisés" },
  { path: "/finance-assurance-dommages", name: "Finance Assurance Dommages", description: "IA pour l'assurance dommages", category: "Secteurs Spécialisés" },
  { path: "/finance-gestion-actifs", name: "Finance Gestion Actifs", description: "IA pour la gestion d'actifs", category: "Secteurs Spécialisés" },
  { path: "/finance-trading-quantitatif", name: "Finance Trading Quantitatif", description: "IA pour le trading quantitatif", category: "Secteurs Spécialisés" },
  { path: "/finance-fintech", name: "Finance FinTech", description: "IA pour les FinTech", category: "Secteurs Spécialisés" },
  { path: "/finance-regtech", name: "Finance RegTech", description: "IA pour la conformité réglementaire", category: "Secteurs Spécialisés" },
  { path: "/finance-insurtech", name: "Finance InsurTech", description: "IA pour l'assurance technologique", category: "Secteurs Spécialisés" },
  { path: "/finance-wealthtech", name: "Finance WealthTech", description: "IA pour la gestion de patrimoine", category: "Secteurs Spécialisés" },
];
